
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp7777
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp7777
  template:
    metadata:
      labels:
        app: nodeapp7777 
    spec:
      containers:
      - name: nodeserver
        image: utube/testing:37a9209
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
