pipeline {
    agent any
    environment {
          DOCKER_TAG = getDockerTag()
          DOCKER_IMAGE = 'utube/testing'
    }
    stages{
        stage('Build Docker Image') {
            steps { 
                 sh 'docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f deploy_k8/Dockerfile . '
            }
         }
        
         stage('DockerHub Push') {
            steps{
               withCredentials([string(credentialsId: 'docker-hub', variable: 'dockerHubPwd')]) {
                 sh "docker login -u utube -p ${dockerhubpwd}"    
                 sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
               }
            }
         }

         stage('Deploy to k8') {
            steps{
                sh 'chmod  +x deploy_k8/changeTag.sh'
                sh './deploy_k8/changeTag.sh ${DOCKER_TAG} '
                sshagent(['ssh-agent']) {
                sh 'scp -o StrictHostKeyChecking=no deploy_k8/change-pod.yml deploy_k8/services.yml kdeploy@35.196.213.141:/home/kdeploy'
                script{
                      try {
                          sh 'ssh kdeploy@35.196.213.141  kubectl apply -f .'
                      }catch(error){
                           sh 'ssh kdeploy@35.196.213.141  kubectl create -f .'
                      }
                }
                }

            }
         }
     } 
}

    

   def getDockerTag(){
        def tag = sh script: 'git rev-parse --short HEAD', returnStdout: true 
        return tag
    } 


 