pipeline {
    agent any
    environment {
          DOCKER_TAG = getDockerTag()
          DOCKER_IMAGE = 'utube/testing'
    }
    stages{
        stage('Build Docker Image') {
            steps { 
                 sh 'docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f push_image/Dockerfile . '
            }
         }
        
         stage('DockerHub Push') {
            steps {
               withCredentials([string(credentialsId: 'docker-hub',  variable: 'dockerhubpwd')]) {
                 sh "docker login -u utube -p ${dockerhubpwd}"    
                 sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
               }
         }
        } 
    }
}
    

   def getDockerTag(){
        def tag = sh script: 'git rev-parse --short HEAD', returnStdout: true 
        return tag
    } 


 