pipeline {
    agent any
    environment {
          DOCKER_TAG = getDockerTag()
          DOCKER_IMAGE = 'utube/testing'
    }
    stages{
        stage('Build Docker Image') {
            steps { 
                 sh 'docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f build_image/Dockerfile . '
            }
         }
    }
}
    def getDockerTag(){
        def tag = sh script: 'git rev-parse --short HEAD', returnStdout: true 
        return tag
    } 
